// Shunde route data. Coordinates are WGS84 reference points for browsing;
// always use the named entrance / shop in a navigation app before departure.
const shundeRoutes = [
  {
    id: "old-town", day: "D1", name: "钟楼站出发 · 老城单向逛吃", color: "#087f72",
    summary: "约 09:15 从大良钟楼站出发，先少量吃金榜，再走清晖园、华盖里和琼花戏楼；赋狮楼只作晚餐备选，最后打车回国泰南路。",
    stops: ["sd-zhonglou", "sd-jinbang", "sd-qinghui", "sd-huagai", "sd-qionghua", "sd-fushilou", "sd-hotel-area"],
    times: ["约 09:15 到达", "09:25 少量早餐", "10:15–11:45", "11:45–12:15", "12:15–14:00", "17:30 有胃口再吃", "约 20:00 回住宿区"],
    segments: ["步行约 10–15 分钟", "步行约 10–15 分钟", "步行约 5 分钟", "步行约 5–8 分钟", "步行约 5–8 分钟", "网约车约 10–15 分钟"]
  },
  {
    id: "park-night", day: "D2-A", name: "大良轻松线 · 公园、博物馆到夜景", color: "#ef6a4b",
    summary: "从国泰南路住宿区出发，凉快时逛顺峰山；午前看顺德博物馆，午间回酒店休息取行李，傍晚去欢乐海岸PLUS。它与 D2-B 容桂线二选一。",
    stops: ["sd-hotel-area", "sd-shunfeng", "sd-museum", "sd-happycoast"],
    times: ["08:15 出发", "08:30–10:30", "11:00–12:30", "16:00–19:00 后返程"],
    segments: ["网约车约 10–15 分钟", "网约车约 10 分钟", "午休取行李后网约车约 5–10 分钟"]
  },
  {
    id: "ronggui-food", day: "D2-B", name: "容桂烟火线 · 排骨饭、旧厂与江边夜食", color: "#5c4bb7",
    summary: "从国泰南路住宿区打车到容边排骨饭吃早午餐；午后可看柴油机1959，傍晚沿渔人码头散步，真饿再吃灵记烧烤。它与 D2-A 大良线二选一。",
    stops: ["sd-hotel-area", "sd-rongbian", "sd-diesel1959", "sd-ronggui-wharf", "sd-lingji-ronggui"],
    times: ["09:00 出发", "09:30–10:45", "12:00–13:15 可选", "16:00–17:30", "17:30 后按胃口"],
    segments: ["网约车约 20–30 分钟（实时导航）", "网约车约 15–25 分钟", "步行约 5–10 分钟", "步行约 5–10 分钟"]
  }
];

// Cross-source shortlist. The 57 Xiaohongshu posts include readable body text
// and loaded comments; 10 official, map and review pages are used to verify
// opening information, addresses and branch names. Rankings are editorial,
// not platform ratings: detailed first-hand accounts and route value outweigh
// bare name lists, engagement counts and promotional wording.
const shundeFoodResearch = {
  sampleSize: 67,
  xhsCount: 57,
  method: "累计去重阅读 57 篇小红书正文及可见评论，并用 10 个官网、地图、门店或游客评价页核对，共 67 条资料。优先采用写清菜品、分店、账单、排队和缺点的实吃记录；纯名单、好评赠品、商业账号与营销式内容降权。排序综合提及频次、具体好评、两人可操作性和本次动线，不等同于平台评分。",
  ranking: [
    { rank: 1, food: "民信老铺（华盖路店）", placeId: "sd-minxin-huagai", signal: "高频甜品", note: "原味或半糖先合点一份；评价分歧也最多" },
    { rank: 2, food: "太艮堡毋米粥（锦龙路总店）", placeId: "sd-wumizhou", signal: "多篇具体实吃", note: "牛展、肉丸、罗氏虾常获好评；价格和油条也有负评" },
    { rank: 3, food: "百益桑拿鸡（大良店）", placeId: "sd-baiyi", signal: "多篇具体实吃", note: "鸡肉、番薯和汤反馈较稳；先问最小份与等位" },
    { rank: 4, food: "容边排骨饭（天河路店）", placeId: "sd-rongbian", signal: "容桂高频", note: "早午餐主选；与御品、达汉珍等近似店名分开" },
    { rank: 5, food: "味可道", placeId: "sd-weikedao", signal: "两篇早茶横评", note: "烧卖、肠粉、粥较受认可；虾饺评价有分歧" },
    { rank: 6, food: "阿多私房菜", placeId: "sd-aduo", signal: "桑拿鸡横评", note: "鸡与汤获具体好评，但价格偏高" },
    { rank: 7, food: "琼花戏楼·顺德菜表演餐厅", placeId: "sd-qionghua", signal: "体验型正餐", note: "顺德菜配表演；优先核对场次和现做菜" },
    { rank: 8, food: "梯底牛乳铺", placeId: "sd-tidi", signal: "甜品横评高频", note: "有人觉得淡而稠，也有人嫌腻；顺路再试" },
    { rank: 9, food: "烧鹅再（大良店）", placeId: "sd-shaoezai", signal: "烧鹅候选", note: "适合小份共享；肥瘦、售罄和排队影响体验" },
    { rank: 10, food: "韦记牛杂（清晖园店）", placeId: "sd-weiji-niuza", signal: "老城顺路", note: "作为华盖路小吃，不为单店长排队" },
    { rank: 11, food: "满登登·顺德特色菜", placeId: "sd-mandengdeng", signal: "容桂本地名单", note: "黄鳝煲仔饭辨识度高；替换主餐，不追加" },
    { rank: 12, food: "乐园酒家", placeId: "sd-leyuan", signal: "容桂老字号", note: "传统早茶和粤菜；更适合早餐或多人分食" },
    { rank: 13, food: "珍之宝御品（渔人码头店）", placeId: "sd-zhenzhibao", signal: "码头便利", note: "位置优势大于口味证据；不想吃烧烤时替换" },
    { rank: 14, food: "红星光发煲仔饭（文海店）", placeId: "sd-hongxing-guangfa", signal: "容桂常见", note: "容边售罄时启用；现煲等待与锅巴评价有分歧" },
    { rank: 15, food: "建港灵记美食·烧烤", placeId: "sd-lingji-ronggui", signal: "码头夜食", note: "先散步，真饿再吃；不把夜食变成任务" },
    { rank: 16, food: "赋狮楼·顺德粥底火锅", placeId: "sd-fushilou", signal: "动线友好", note: "离老城主线近；与太艮堡二选一" },
    { rank: 17, food: "新顺发鱼店（熟制点法）", placeId: "sd-xinshunfa", signal: "鱼类高频", note: "生鱼不进主路线，只考虑彻底熟制的一鱼多吃" },
    { rank: 18, food: "大围公早餐", placeId: "sd-dawaigong", signal: "街坊早餐", note: "粥、肉碎肠粉、油条和豆浆；只在愿意早起时" },
    { rank: 19, food: "顺峰山庄", placeId: "sd-shunfeng-restaurant", signal: "传统粤菜", note: "多人更合适；两人先问小份、茶位和服务费" },
    { rank: 20, food: "金榜上街", placeId: "sd-jinbang", signal: "小吃聚集区", note: "不是单一神店；奶制品只选一两样共享" }
  ],
  playRanking: [
    { rank: 1, placeId: "sd-qinghui", note: "岭南园林核心；上午入园体验更稳" },
    { rank: 2, placeId: "sd-shunfeng", note: "免费湖景与牌坊；不用硬走完整环线" },
    { rank: 3, placeId: "sd-huagai", note: "骑楼老街与支巷，和清晖园自然连走" },
    { rank: 4, placeId: "sd-jinbang", note: "老街与水牛奶文化，小份探索即可" },
    { rank: 5, placeId: "sd-ronggui-wharf", note: "旧码头、墙绘与日落；傍晚优于正午" },
    { rank: 6, placeId: "sd-happycoast", note: "夜景、摩天轮和免费街区，付费项目按需" },
    { rank: 7, placeId: "sd-fengjian", note: "水乡桥巷；非自驾需单独留半天" },
    { rank: 8, placeId: "sd-museum", note: "顺德历史与产业背景，正午室内段" },
    { rank: 9, placeId: "sd-diesel1959", note: "容桂工业遗存；与渔人码头一起看" },
    { rank: 10, placeId: "sd-hem", note: "建筑与当代艺术；北滘单独成线" },
    { rank: 11, placeId: "sd-lingnan-heyuan", note: "岭南园林与非遗展示；和美术馆附近" },
    { rank: 12, placeId: "sd-bijiang-jinlou", note: "金漆木雕与古建；适合历史建筑爱好者" },
    { rank: 13, placeId: "sd-baolin", note: "寺院和山地视角；要接受台阶与坡度" },
    { rank: 14, placeId: "sd-desheng-river", note: "安静河岸，替换欢乐海岸而不是叠加" },
    { rank: 15, placeId: "sd-lunjiao-678", note: "旧街活化与香云纱片区，适合慢逛" },
    { rank: 16, placeId: "sd-fengling", note: "老城绿地；顺路休息，不必专程" },
    { rank: 17, placeId: "sd-xishan-temple", note: "靠近钟楼站的古建小支线" },
    { rank: 18, placeId: "sd-xiangyunsha", note: "香云纱工艺专题；先核开放与预约" },
    { rank: 19, placeId: "sd-brucelee", note: "功夫文化主题；均安较远，需单独成线" },
    { rank: 20, placeId: "sd-snoopy", note: "亲子主题乐园；无儿童同行时优先级较低" }
  ],
  sources: [
    ["01｜顺德两天一夜！避雷&强推都在这篇了！", "https://www.xiaohongshu.com/explore/6a0599ef0000000037037bb7"],
    ["02｜顺德美食红黑榜（游客版）", "https://www.xiaohongshu.com/explore/6a587c76000000000f02b7b4"],
    ["03｜2026.1.1-1.3 顺德Trip：别瞎信‘遍地美食’", "https://www.xiaohongshu.com/explore/695cd366000000000a03dfb8"],
    ["04｜将不会再给清晖园及周边网红店第二次机会", "https://www.xiaohongshu.com/explore/6aa53b69000000002a0279e8"],
    ["05｜顺德2天无广纯吃", "https://www.xiaohongshu.com/explore/69722beb00000000220201d3"],
    ["06｜顺德美食大实话测评", "https://www.xiaohongshu.com/explore/6a68e3c200000000110052ed"],
    ["07｜顺德两天两夜纯吃打分点评", "https://www.xiaohongshu.com/explore/6a7722ee000000002402e312"],
    ["08｜两天一夜的顺德美食结算", "https://www.xiaohongshu.com/explore/6aa81222000000002603ad12"],
    ["09｜深圳到顺德2天1夜干饭攻略", "https://www.xiaohongshu.com/explore/6aa28fd9000000002b01e120"],
    ["10｜顺德48小时纯吃不逛", "https://www.xiaohongshu.com/explore/69ede1580000000035028cc5"],
    ["11｜顺德两天吃了12顿居然才花了500多", "https://www.xiaohongshu.com/explore/6a6c90b7000000000502bbe7"],
    ["12｜顺德两天纯吃攻略", "https://www.xiaohongshu.com/explore/6a015581000000003601d01c"],
    ["13｜人均300在大良北滘两天一夜吃了啥", "https://www.xiaohongshu.com/explore/6a01aaa2000000003503a798"],
    ["14｜香港出发｜顺德两天一夜游", "https://www.xiaohongshu.com/explore/6a1cf951000000000702b2b8"],
    ["15｜去了顺德5次，总结没有提过的雷", "https://www.xiaohongshu.com/explore/6a7ea4570000000032030bca"],
    ["16｜外地人吃了四家烧鹅的真实排名", "https://www.xiaohongshu.com/explore/6a658e0200000000110105c2"],
    ["17｜顺德美食避雷", "https://www.xiaohongshu.com/explore/6aa16774000000000b00f1e6"],
    ["18｜顺德两晚四顿饭综合评价", "https://www.xiaohongshu.com/explore/6a33807b000000001503e0d7"],
    ["19｜顺德结算 推荐与避雷", "https://www.xiaohongshu.com/explore/6a40e2f90000000006033dfe"],
    ["20｜这是一篇踩雷篇", "https://www.xiaohongshu.com/explore/69d7d280000000002200ed42"],
    ["21｜顺德三天两夜一人吃喝攻略", "https://www.xiaohongshu.com/explore/69ef14a3000000002202a89d"],
    ["22｜五一顺德吃什么 土著推荐", "https://www.xiaohongshu.com/explore/69f5e07d0000000035028e45"],
    ["23｜顺德本地人私藏好店合集", "https://www.xiaohongshu.com/explore/69edbcc8000000003601e325"],
    ["24｜顺德真的好好吃啊", "https://www.xiaohongshu.com/explore/6a76981000000000330128e0"],
    ["25｜吃完就想二刷这些店", "https://www.xiaohongshu.com/explore/6a733b09000000000f039800"],
    ["26｜来顺德只吃一顿饭我的建议是", "https://www.xiaohongshu.com/explore/6a89178f0000000017000efd"],
    ["27｜顺德早茶篇 味可道 德景轩", "https://www.xiaohongshu.com/explore/6a2169d7000000003703688b"],
    ["28｜顺德早茶亲测 聚福山庄 味可道", "https://www.xiaohongshu.com/explore/69abc64c000000002602d901"],
    ["29｜顺德平价早茶珍之宝测评", "https://www.xiaohongshu.com/explore/6a8b03e50000000028028379"],
    ["30｜顺德金榜街双皮奶三家横评", "https://www.xiaohongshu.com/explore/6a6ef01e000000002403fd2a"],
    ["31｜在顺德吃了三家双皮奶总结", "https://www.xiaohongshu.com/explore/6a7320c000000000220170b2"],
    ["32｜每天两碗 顺德双皮奶大测评", "https://www.xiaohongshu.com/explore/697c5aca0000000028021ec7"],
    ["33｜顺德老字号桑拿鸡测评", "https://www.xiaohongshu.com/explore/6a82dac50000000025000fb8"],
    ["34｜顺德美食不完全评鉴", "https://www.xiaohongshu.com/explore/6a2038d4000000003501e483"],
    ["35｜顺德刚回 说一点个人的想法", "https://www.xiaohongshu.com/explore/6aa9e0f6000000002502fa8d"],
    ["36｜顺德第一天踩雷了", "https://www.xiaohongshu.com/explore/6aab7e79000000000b00fc72"],
    ["37｜两次用餐后对美食之都失望", "https://www.xiaohongshu.com/explore/699b36ea000000000a0287c0"],
    ["38｜顺德两家大踩雷", "https://www.xiaohongshu.com/explore/69847b2c0000000022020c85"],
    ["39｜顺德去了，感觉不尽人意", "https://www.xiaohongshu.com/explore/694249d8000000001f007f3f"],
    ["40｜深圳—顺德工作日二日游交通避雷", "https://www.xiaohongshu.com/explore/69c20ed6000000001a0357cd"],
    ["41｜顺德两天一夜 路边停车大冒险", "https://www.xiaohongshu.com/explore/6a30a4d8000000000f005cca"],
    ["42｜低精力吃货顺德一日游", "https://www.xiaohongshu.com/explore/6a783d1900000000270215ee"],
    ["43｜深圳到顺德2天1夜路线", "https://www.xiaohongshu.com/explore/6958a1250000000021029c71"],
    ["44｜人均低于500的顺德路线", "https://www.xiaohongshu.com/explore/6a045f660000000036001a36"],
    ["45｜园林古建+老街美食", "https://www.xiaohongshu.com/explore/6aac1cdf0000000028038043"],
    ["46｜顺德渔人码头一日游", "https://www.xiaohongshu.com/explore/6aaded86000000000d027f2a"],
    ["47｜本地人带你逛大良一日游", "https://www.xiaohongshu.com/explore/6a914219000000002c03e799"],
    ["48｜顺德清晖园48小时纯吃攻略", "https://www.xiaohongshu.com/explore/69edda7a0000000036000d7e"],
    ["49｜本地人带路 两天吃遍顺德", "https://www.xiaohongshu.com/explore/6aae46f9000000002502e029"],
    ["50｜适合外地人的顺德美食攻略", "https://www.xiaohongshu.com/explore/69c3d7b70000000023023695"],
    ["51｜顺德一日游去哪里", "https://www.xiaohongshu.com/explore/69dc93ff00000000230140e5"],
    ["52｜顺德两天一夜Citywalk", "https://www.xiaohongshu.com/explore/696c5151000000000e00e27d"],
    ["53｜广东旅行 佛山顺德篇", "https://www.xiaohongshu.com/explore/698498df000000000b0088fa"],
    ["54｜二刷顺德住宿酒店推荐", "https://www.xiaohongshu.com/explore/698fe6f4000000000a028147"],
    ["55｜顺德2日特种兵攻略", "https://www.xiaohongshu.com/explore/6a6c71a8000000002903272b"],
    ["56｜深圳到顺德交通攻略", "https://www.xiaohongshu.com/explore/6a43269e00000000160243ba"],
    ["57｜35元深圳往返顺德", "https://www.xiaohongshu.com/explore/69789ef6000000000a03ffb8"],
    ["58｜清晖园官方开放与票务", "https://www.sdqinghuiyuan.cn/"],
    ["59｜顺德博物馆官方资讯", "https://www.sdmuseum.com.cn/inforlist.html"],
    ["60｜容桂街道办：渔人码头", "https://www.shunde.gov.cn/fssdrg/gkmlpt/content/6/6035/post_6035900.html#3831"],
    ["61｜欢乐海岸PLUS官网", "https://www.octharbourplus.com/"],
    ["62｜和美术馆官网", "https://www.hem.org/"],
    ["63｜广东疾控：淡水鱼生风险", "https://cdcp.gd.gov.cn/ywdt/dt/content/post_4147086.html"],
    ["64｜容边排骨饭门店与评价", "https://m.dianping.com/shop/94281484?msource=applemaps"],
    ["65｜百益桑拿鸡大良店", "https://m.dianping.com/shop/1441139188?msource=applemaps"],
    ["66｜太艮堡毋米粥门店", "https://ditu.amap.com/place/B0FFFAGO10"],
    ["67｜红星光发游客评论", "https://you.ctrip.com/food/foshan207/5491941-dianping187199811.html"]
  ]
};

const shundeUpdates = {
  "sd-qinghui": {
    category: "人文", area: "大良老城", lat: 22.8383866, lng: 113.2498286,
    transit: "清晖路 23 号；从金榜上街步行约 10–15 分钟",
    summary: "钟楼站与金榜之后的上午主景点；只走核心庭院，给午餐和老街留体力。",
    description: "清晖园不是这次的起点，而是从大良钟楼站、金榜上街走来的上午主景点。按回廊、池水和庭院慢走一圈即可，不必每个角落都到。",
    features: "岭南园林、灰塑与水院空间集中，阴影较多，适合上午慢慢看。",
    playability: "看建筑细节、拍回廊倒影；时间紧时只走核心庭院，约 90 分钟也够形成完整体验。",
    itinerary: ["约 10:15 到清晖路 23 号入口，先看当天开放与购票信息。", "沿回廊慢走核心庭院，不追求全部打卡。", "从清晖路一侧离开，步行接华盖里和琼花戏楼。"],
    tips: ["地图点位是园区中心，进园请导航清晖路 23 号入口。", "官网通常公布开放、票务与分时段信息；临时限流以当天公告为准。", "若钟楼站抵达晚于 10 点，压缩金榜停留，不压缩已预约的琼花场次。"],
    source: "https://www.sdqinghuiyuan.cn/",
    researchSources: [["清晖园官方网站：开放与票务", "https://www.sdqinghuiyuan.cn/"], ["Trip 游客评价与停留参考", "https://hk.trip.com/travel-guide/attraction/foshan/qinghui-garden-museum-82949/"]]
  },
  "sd-jinbang": {
    name: "金榜上街", category: "美食", area: "大良老城", lat: 22.8402481, lng: 113.2425951,
    duration: "45–75 分钟", best: "D1 到达后少量早餐", transit: "从大良钟楼站步行约 10–15 分钟",
    summary: "钟楼站后的第一站；奶制品与小食只选一两样分食，不要一早吃撑。",
    description: "金榜上街不是只为一家店而来。先沿街看当天开门、排队和菜单，再从双皮奶、水牛奶或炸物里选一两样分食；口味评价分歧很大，现场判断比照着单一榜单更稳。",
    features: "老街尺度小，奶制甜品与顺德小食集中，适合边走边选。",
    playability: "比较同类甜品或只喝一份奶制品，把胃口留给琼花戏楼正餐。",
    food: "探索重点：原味双皮奶、姜撞奶、水牛奶或炸牛奶；两个人合点一份，先看现做批次与甜度。",
    itinerary: ["从大良钟楼站步行到金榜上街。", "先完整看一圈，再选 1–2 样分食。", "约 10:00 离开，步行去清晖园。"],
    tips: ["老街店铺与营业时段变化快，以当天门店为准。", "热门店排队长就换同类小店，不必执着单一招牌。", "奶制品连吃容易腻，D1 早餐严格控制份量。"],
    source: "https://www.openstreetmap.org/way/630652975",
    researchSources: [["金榜上街游客路线与近期体验", "https://my.trip.com/moments/detail/foshan-207-144480653?locale=zh-MY"], ["手工水牛奶制作背景", "https://www.thepaper.cn/newsDetail_forward_8840075"], ["金榜上街小食实走视频", "https://www.youtube.com/watch?v=TK8zVWJmUB4"]]
  }
};

Object.entries(shundeUpdates).forEach(([id, update]) => {
  const place = extraPlaces.find(item => item.id === id);
  if (place) Object.assign(place, update);
});

extraPlaces.push(...[
  {
    id: "sd-zhonglou", city: "顺德", area: "大良老城", category: "交通",
    name: "大良钟楼站（D1 起点）", lat: 22.8422296, lng: 113.2477468,
    duration: "10–15 分钟", best: "D1 约 09:15", transit: "佛山地铁 3 号线大良钟楼站",
    summary: "第一天明确起点；出站后直接向西走金榜上街，不先绕清晖园。",
    description: "把抵达时间、洗手间和补水都在车站解决，再开始老城单向步行。地图从这里画出第一天的完整动线。",
    features: "离金榜、清晖园与华盖路都近，是大良老城最清楚的集合点。",
    playability: "不在站外反复找早餐；先走金榜，之后顺着老城一路向东南。",
    itinerary: ["约 09:15 到站，出站前完成补水和整理。", "导航金榜上街，步行约 10–15 分钟。", "若到得晚，直接去清晖园，把金榜留到下午。"],
    tips: ["具体出口以当天站内导向和导航为准。", "第一天大部分为步行，行李建议先寄存或只带轻装。", "地图时间是留有余量的旅行时间，不是列车时刻。"],
    source: "https://www.openstreetmap.org/way/908822773"
  },
  {
    id: "sd-hotel-area", city: "顺德", area: "大良新城", category: "住宿",
    name: "国泰南路住宿区（暂定锚点）", lat: 22.8004, lng: 113.2970,
    duration: "住宿 / 午休", best: "D1 夜间、D2 两线起点", transit: "国泰南路 1–6 号一带；收到酒店名后可替换成精确入口",
    summary: "当前按国泰南路中段作住宿锚点；D2 可选大良公园夜景线，也可直接去容桂吃喝散步。",
    description: "国泰南路很长，当前地图针取 1–6 号一带的中间参考点，不冒充你的酒店门口。这里靠近顺德博物馆与欢乐海岸PLUS；若选容桂线，则把它当作早上叫车出发的锚点。",
    features: "把住宿区加入动线后，D1 不必在老城兜圈；D2-A 可紧凑衔接大良新城，D2-B 则直接向南去容桂。",
    playability: "选 D2-A 可午间回房补水取行李；选 D2-B 则带好行李或先确认寄存，避免傍晚折返大良。",
    itinerary: ["D1 晚餐后网约车回住宿区。", "D2-A：早上去顺峰山，博物馆后回酒店午休取行李。", "D2-B：约 09:00 直接打车去容边排骨饭，之后留在容桂，不再折返大良。"],
    tips: ["这是区域锚点，不是精确酒店入口。", "提供酒店全名后再校正地图针和每段车程。", "退房和寄存时间以酒店当天规则为准。"],
    source: "https://foshanshunde-octharbourplus.orangehotels.cn/"
  },
  {
    id: "sd-huagai", city: "顺德", area: "大良老城", category: "人文",
    name: "华盖里 / 华盖路步行街", lat: 22.8376018, lng: 113.2496924,
    duration: "30–60 分钟", best: "清晖园之后", transit: "从清晖园步行约 5 分钟",
    summary: "骑楼、支巷与小吃连在一起；它是清晖园到琼花戏楼的缓冲段，不另作折返打卡。",
    description: "把华盖里当作清晖园与琼花戏楼之间的连接。主街容易走，支巷更有生活感；先散步观察，不在正餐前连续吃小吃。",
    features: "骑楼老街、日常店铺与旅游小吃混在一起，适合无压力地闲逛。",
    playability: "看骑楼、逛一条支巷、随机选一份小食；不需要固定打卡顺序。",
    food: "可留意牛杂、鱼皮、伦教糕与凉茶；琼花戏楼已订餐时只看不多吃。",
    itinerary: ["清晖园出来后转入华盖里。", "沿骑楼阴影慢走，不来回刷街。", "按预约时间去华盖里四巷 14 号琼花戏楼。"],
    tips: ["这是街区参考点，店铺位置和营业会变。", "正午较晒，优先走骑楼阴影处。", "主餐前只买小份，把探索空间留给正餐。"],
    source: "https://www.openstreetmap.org/"
  },
  {
    id: "sd-qionghua", city: "顺德", area: "大良老城", category: "美食",
    name: "琼花戏楼·顺德菜表演餐厅", lat: 22.8342, lng: 113.2552,
    duration: "1.5–2 小时", best: "D1 主午餐；按当天演出预约", transit: "华盖里四巷 14 号；从华盖路步行约 5–8 分钟",
    summary: "D1 的主餐：顺德菜、广式茶点配粤剧、醒狮等表演；场次不合时再把它调整到晚餐。",
    description: "琼花戏楼放在老城步行线的中段最顺。先向店家确认当天演出场次、订座和消费规则；若午场不合适，可与赋狮楼调换主次，但一天不安排两顿大正餐。",
    features: "顺德菜与戏楼演出结合，公开介绍提到粤剧、醒狮等节目；节目与演员以当天安排为准。",
    playability: "一顿饭同时体验地方餐饮与表演；时间不合也可只把这里作为备选餐厅。",
    food: "探索重点：顺德菜、广式茶点；按两人份量点菜，先问哪些菜为现点现做。",
    itinerary: ["从华盖里步行到华盖里四巷 14 号。", "到店确认演出场次、座位和消费规则，再点适合人数的菜。", "餐后慢走老城；若已经饱，取消赋狮楼。"],
    tips: ["地图针按街巷相邻门牌插值，找店请用完整地址。", "演出时段与座位视线可能变化，出发前向店家确认。", "本地图不保证所有菜品均现做；介意预制时逐道询问制作与备料方式。"],
    source: "https://m.dahepiao.com/jingqu/qhxlcg/",
    researchSources: [["琼花戏楼地址与公开演出介绍", "https://m.dahepiao.com/jingqu/qhxlcg/"]]
  },
  {
    id: "sd-fushilou", city: "顺德", area: "大良", category: "美食",
    name: "赋狮楼·顺德粥底火锅", lat: 22.831814003011843, lng: 113.25435201576364,
    duration: "1.5–2 小时", best: "D1 晚餐备选；有胃口再去", transit: "碧鉴路 56 号；从琼花戏楼步行约 5–8 分钟",
    summary: "粥底火锅作为晚餐备选，不与琼花戏楼强行连吃两顿大餐。",
    description: "若午餐较早、下午继续逛且晚上确实饿，再来吃粥底火锅；否则直接回酒店，把它留作下次。先确认当天食材、份量和计价，再少量分批下锅。",
    features: "顺德粥底火锅，重点是清粥底、分批涮食材和最后吸收鲜味的粥。",
    playability: "两个人选一到两种主料，加一份蔬菜或油条，避免为了尝全菜单点太多。",
    food: "建议探索：粥底、鱼片或鸡肉、时蔬、油条；鲜活情况与计价以当天菜单为准。",
    itinerary: ["先判断午餐后的真实饥饿程度。", "有胃口再到店看菜单和等位；不饿就跳过。", "晚餐后网约车回国泰南路住宿区。"],
    tips: ["地址已核到碧鉴路 56 号，导航当日结果优先。", "介意预制时可现场逐道询问制作与备料方式。", "龙的酒楼按你的偏好不纳入路线；本项目也不对其制作方式作未经核实的断言。"],
    source: "https://map.qq.com/m/detail/poi/poid=6739000127798680704"
  },
  {
    id: "sd-minxin-huagai", city: "顺德", area: "大良老城", category: "美食",
    name: "民信老铺（华盖路店）", pinName: "★双皮奶｜民信老铺", lat: 22.8371528, lng: 113.2485551,
    duration: "20–40 分钟", best: "D1 老城段分食一份", transit: "华盖路 115–119 号一带；清晖园与华盖里步行可达",
    summary: "甜品样本中提及很集中，但评价分歧也最多；原味双皮奶优先，两个人分一份后再决定要不要加炸牛奶。",
    description: "这里作为高频菜“落到地图”的代表点，不代表它一定胜过金榜小店。样本对双皮奶甜度、奶味和排队价值评价分歧明显，所以把它安排为小份比较，而不是必须完成的打卡任务。",
    features: "双皮奶、姜撞奶、炸牛奶等水牛奶甜品集中，位置与 D1 老城线重合。",
    playability: "先点一份原味双皮奶，两个人试过甜度和奶味后，再决定是否加第二样。",
    food: "水牛奶甜品是样本中的高频类别；原味双皮奶优先，炸牛奶或炒牛奶只作共享加项。",
    itinerary: ["清晖园或华盖里途中顺路到店。", "先合点一份原味双皮奶。", "若琼花戏楼即将开餐，不再追加炸物。"],
    tips: ["地址资料在华盖路 115–119 号与华盖里 1 号两种写法间有差异，地图针按华盖里街内 OSM 门店点标注，导航时核对店名。", "榜单名次是跨来源综合结果，不是平台评分。", "甜度和口感高度主观，排队过长时金榜上街同类小店可以替代。"],
    source: "https://hk.trip.com/restaurant/china/foshan/detail/minxin-old-shop-10561901/",
    researchSources: [["Trip：门店地址与游客评价", "https://hk.trip.com/"], ["永安旅游：华盖路店地址", "https://www.wingontravel.com/"], ["大良水牛奶与双皮奶背景", "https://www.thepaper.cn/newsDetail_forward_8840075"]]
  },
  {
    id: "sd-wumizhou", city: "顺德", area: "大良老城西北", category: "美食",
    name: "太艮堡毋米粥（锦龙路总店）", pinName: "★粥底火锅｜毋米粥", lat: 22.8520517, lng: 113.2367342,
    duration: "1.5–2 小时", best: "单独作为一顿正餐", transit: "锦龙路 270 号；从钟楼/金榜短途网约车更省力",
    summary: "第二高频正餐；与赋狮楼同属粥底火锅路线，两家二选一，不要为了榜单连续吃。",
    description: "把食材按海鲜、肉、蔬菜的顺序少量分批涮，最后喝粥底。它位于老城西北侧，若 D1 已预约琼花戏楼，不建议再为它改主线；可作为琼花场次不合适时的替换正餐。",
    features: "“有米不见米”的粥水锅底，重点在食材下锅顺序和最后吸收鲜味的粥。",
    playability: "两个人选一到两种主料即可；先问份量、计价、茶位与当天鲜活食材。",
    food: "粥底火锅在样本中提及集中；代表吃法是一鲜、二荤、三素、最后喝粥。",
    itinerary: ["只在替换一顿正餐时加入。", "到店先问两人份量和当天食材。", "吃完直接按下一站叫车，不再追加赋狮楼。"],
    tips: ["地图坐标由公开地图坐标转换为 WGS84，找入口仍以锦龙路 270 号导航为准。", "与赋狮楼功能重叠，二选一。", "介意预制时逐道询问丸滑、小吃与配菜的制作方式。"],
    source: "https://www.amap.com/place/B0FFH7FW5P",
    researchSources: [["Klook：粥底火锅介绍与锦龙路地址", "https://www.klook.com/zh-HK/blog/foshan-food/"], ["OpenRice：锦龙路 270 号门店资料", "https://www.openrice.com.cn/"]]
  },
  {
    id: "sd-xinshunfa", city: "顺德", area: "大良南部", category: "美食",
    name: "新顺发鱼店·金牌鱼生（大良店）", pinName: "★鱼生｜新顺发", lat: 22.8177, lng: 113.2548,
    duration: "1.5–2 小时", best: "明确接受生食风险时", transit: "同兴路 8 号广地商贸城 3 栋 175–180 铺；建议网约车",
    summary: "第三高频，但淡水鱼生并非必吃项；地图保留探索点，主路线默认不安排。",
    description: "公开资料常写一鱼多吃：鱼生、鱼皮、骨腩和鱼粥。但生食淡水鱼存在寄生虫风险，不能靠“现杀”“看起来新鲜”消除；不接受风险时，点熟食鱼、鱼皮或鱼粥即可。",
    features: "一鱼多吃和刀工体验集中；地点离 D1 老城核心、D2 住宿区都需要打车。",
    playability: "把它视为有明确风险偏好的可选正餐，不为“高频”勉强尝生食。",
    food: "鱼生与一鱼多吃在样本中提及较多，但提及高不等于风险低；可只选彻底熟制菜。",
    itinerary: ["决定前先确认所有同行者都接受淡水鱼生风险。", "不接受时只点彻底熟制的一鱼多吃菜式。", "加入本店就替换一顿正餐，不与琼花、赋狮楼叠加。"],
    tips: ["地图针按同兴路与商贸城公开地址近似标注，导航请用完整店名和门牌。", "孕妇、儿童、老年人及免疫力较弱者不建议生食。", "鱼生高频不等于低风险，本地图默认不把它列入主路线。"],
    source: "https://www.openrice.com/zh/foshan/r-%E6%96%B0%E9%A0%86%E7%99%BC%E9%AD%9A%E5%BA%97-%E9%87%91%E7%89%8C%E9%AD%9A%E7%94%9F-%E5%A4%A7%E8%89%AF-%E7%B2%B5%E8%8F%9C-%E5%BB%A3%E6%9D%B1-r8364551",
    researchSources: [["OpenRice：门店地址、营业段与招牌菜", "https://www.openrice.com/zh/foshan/r-%E6%96%B0%E9%A0%86%E7%99%BC%E9%AD%9A%E5%BA%97-%E9%87%91%E7%89%8C%E9%AD%9A%E7%94%9F-%E5%A4%A7%E8%89%AF-%E7%B2%B5%E8%8F%9C-%E5%BB%A3%E6%9D%B1-r8364551"], ["香港01：一鱼多吃与地址", "https://global.hk01.com/%E6%97%85%E6%B8%B8/60351471/%E4%BD%9B%E5%B1%B1%E7%BE%8E%E9%A3%9F10%E5%A4%A7%E6%8E%A8%E4%BB%8B-%E9%9D%9E%E9%81%97%E7%B2%A5%E5%BA%95%E7%81%AB%E9%94%85-%E9%A1%BA%E5%BE%B7%E9%B1%BC%E7%94%9F-%E6%A1%91%E6%8B%BF%E9%B8%A1-%E6%AD%A3%E5%AE%97%E5%8F%8C%E7%9A%AE%E5%A5%B6"]]
  },
  {
    id: "sd-baiyi", city: "顺德", area: "大良老城西侧", category: "美食",
    name: "百益桑拿鸡（大良店）", pinName: "★桑拿鸡｜百益", lat: 22.8426, lng: 113.2436,
    duration: "1.5–2 小时", best: "提前取号，替换一顿正餐", transit: "凤山中路 47 号附近；靠近金榜商圈，地图针为门牌路段参考",
    summary: "第四高频，蒸气现熟是它的体验重点；排队和份量反馈分歧较大，作为正餐替换项。",
    description: "桑拿鸡以蒸气短时蒸熟鸡肉，汁水落入下层汤底。公开攻略反复提及百益大良店，但游客反馈也常提到热门时段等位，因此不把它与琼花戏楼、粥底火锅连续安排。",
    features: "蒸气鸡、下层汤底和分批现蒸的过程感明显，适合两人共享。",
    playability: "选鸡肉加一两份蔬菜即可；先问最小份量、等位和收费项目。",
    food: "桑拿鸡在样本中提及较多；先吃鸡、再蒸菜、最后喝吸收肉汁的汤底。",
    itinerary: ["D1 在金榜附近先看等位。", "若选择本店，就替换琼花或当日晚餐，不追加第二顿正餐。", "饭后再按体力回老城或直接去住宿区。"],
    tips: ["公开资料写作凤山中路 47 号附近；地图针按该路段近似标注，入口以导航为准。", "热门时段可能排队，先看现场再决定。", "介意预制时重点询问丸滑、腌制小吃和配菜；鸡肉现蒸不代表全桌所有菜都现制。"],
    source: "https://m.dianping.com/shop/1441139188?msource=applemaps",
    researchSources: [["Klook：百益大良店地址与桑拿鸡吃法", "https://www.klook.com/zh-HK/blog/foshan-food/"], ["大众点评：大良店门店页", "https://m.dianping.com/shop/1441139188?msource=applemaps"]]
  },
  {
    id: "sd-shunfeng", city: "顺德", area: "大良", category: "公园",
    name: "顺峰山公园", lat: 22.8303153, lng: 113.2736278,
    duration: "1.5–2 小时", best: "D2 早上", transit: "从国泰南路住宿区网约车约 10–15 分钟",
    summary: "凉快时只走牌坊、近湖步道与青云塔视角，不完整环湖。",
    description: "公园很大，省力玩法是把主入口牌坊、近湖步道和青云塔视角作为核心，走到体感合适就返回。上午比下午更利于控制暴晒与体力。",
    features: "大型牌坊、湖面、草地与远处青云塔同框，是顺德城市尺度最开阔的一站。",
    playability: "散步、拍牌坊与湖景、坐草地休息；不必为了“逛完”走到远端。",
    itinerary: ["约 08:30 从主入口进入。", "沿近湖步道选一小段慢走，不完整环湖。", "约 10:30 在主入口叫车去顺德博物馆。"],
    tips: ["地图点为主入口附近，不是整个公园中心。", "宝林寺只在愿意爬台阶时加，不列入主线。", "晴天仍要防晒与补水。"],
    source: "https://www.openstreetmap.org/relation/17231340",
    researchSources: [["顺峰山公园近年更新与公共空间", "https://epaper.nfnews.com/m/ipaper/nfrb/html/202502/28/content_10128222.html"], ["游客停留时间与步行体验", "https://cn.tripadvisor.com/Attraction_Review-g494927-d1843415-Reviews-Mt_Shunfeng_Park-Foshan_Guangdong.html"]]
  },
  {
    id: "sd-museum", city: "顺德", area: "大良新城", category: "人文",
    name: "顺德博物馆", lat: 22.8017452, lng: 113.2883393,
    duration: "1–1.5 小时", best: "D2 11:00 左右", transit: "从顺峰山公园网约车约 10 分钟；靠近国泰南路住宿区",
    summary: "午前转入室内，快速建立顺德历史、产业与民俗背景；遇闭馆则直接回酒店休息。",
    description: "把博物馆放在顺峰山之后，可避开正午热度，也与国泰南路住宿区在同一片区。展览和预约规则会变，出发前查看当天开放信息。",
    features: "地方历史、民俗与产业主题集中，适合在吃喝之外补一段顺德背景。",
    playability: "先看常设展导览图，只选最感兴趣的两三个展区，不追求逐柜看完。",
    itinerary: ["约 11:00 到馆，先确认预约与最后入馆时间。", "用 60–90 分钟看常设展重点。", "约 12:30 回国泰南路午休、取行李。"],
    tips: ["开放日、预约和临展以博物馆当天公告为准。", "若闭馆或预约已满，直接回酒店，不额外折返。", "地图点为建筑参考点，入口按现场导向。"],
    source: "https://www.sdmuseum.com.cn/inforlist.html",
    researchSources: [["顺德博物馆官方资讯", "https://www.sdmuseum.com.cn/inforlist.html"], ["开放与游客停留参考", "https://www.trip.com/travel-guide/attraction/foshan/shunde-museum-24652885?curr=TWD&locale=zh-HK"]]
  },
  {
    id: "sd-happycoast", city: "顺德", area: "大良新城", category: "乐园",
    name: "欢乐海岸PLUS", lat: 22.8184964, lng: 113.2993887,
    duration: "3–4 小时", best: "D2 16:00 到夜间", transit: "欢乐大道 1 号；从国泰南路住宿区网约车约 5–10 分钟",
    summary: "傍晚看摩天轮与街区亮灯；免费街区和付费项目分开选，19 点后按真实返程站出发。",
    description: "午间回酒店休息、取行李后再来。先逛开放街区、看摩天轮和灯光，再根据排队和体力决定是否购买一个主题项目；不把每个园区都塞进同一天。",
    features: "摩天轮、曲水湾街区、餐饮与主题项目集中，夜间氛围比白天完整。",
    playability: "可只逛街区和吃饭，也可选一两个付费项目；最后直接去实际返程站。",
    food: "园区餐饮更偏便利；想把晚餐留给真正想吃的顺德菜，可先查好店再来散步。",
    itinerary: ["约 16:00 到达，先逛免费街区。", "看亮灯与摩天轮，再选一个真正想玩的项目。", "约 19:00 后按车票与真实返程站导航，不预设终点。"],
    tips: ["顺德欢乐海岸PLUS与深圳欢乐海岸不是同一地点。", "各票种、项目与开放季节不同，购票前核对名称。", "返程站尚未确定，务必按车票倒推离园时间。"],
    source: "https://www.octharbourplus.com/",
    researchSources: [["欢乐海岸PLUS官方网站", "https://www.octharbourplus.com/"]]
  },
  {
    id: "sd-dawaigong", city: "顺德", area: "大良", category: "美食",
    name: "大围公早餐（可选支线）", lat: 22.8390, lng: 113.2590,
    duration: "45–60 分钟", best: "想吃本地早餐时早去", transit: "大围六街三巷 10 号之一；近东乐路站，地图针为街巷参考",
    summary: "粥、肉碎肠粉、油条、豆浆等早餐；不顺 D1 钟楼起点，列作 D2 早起支线而非主线。",
    description: "如果愿意早起，可从酒店打车先吃早餐，再去顺峰山；若想省力，直接酒店早餐即可。把它放进备选而不是主线，是为了避免为一顿早餐多绕路。",
    features: "传统街坊早餐组合，适合两人分点几样，不必各点一整套。",
    playability: "观察当天出品和街坊点单，再选粥、肠粉与油条中的两三样分食。",
    food: "探索重点：粥、肉碎肠粉、油条、豆浆；价格与供应以当天为准。",
    itinerary: ["仅在愿意 07:30 左右出门时加入。", "早餐后网约车去顺峰山公园。", "不早起就跳过，不影响主线。"],
    tips: ["地图针为街巷参考，找店请导航完整地址。", "早餐档营业与售罄时间可能变化，出发前复核。", "不要为了早餐牺牲整天体力。"],
    source: "https://content.foshanplus.com/",
    researchSources: [["本地早餐实走视频", "https://www.youtube.com/watch?v=PTHqsKPwPTc"]]
  },
  {
    id: "sd-shunfeng-restaurant", city: "顺德", area: "大良", category: "美食",
    name: "顺峰山庄（多人餐备选）", lat: 22.8038716, lng: 113.2632101,
    duration: "1.5–2 小时", best: "多人聚餐或想坐下吃传统粤菜时", transit: "105 国道与果园街交叉口西北侧；建议网约车",
    summary: "传统粤菜与点心备选，更适合多人；两个人去要先问茶位、服务费与小份菜。",
    description: "这类山庄式餐厅适合想坐下来吃完整一餐或多人分菜。两个人也能去，但要控制份量，不把它硬塞进已经有琼花戏楼与赋狮楼的主线。",
    features: "传统粤菜、点心与较完整的宴席环境。",
    playability: "看当天点心与烧味供应，优先选能分食的小份菜。",
    food: "探索重点可放在点心、烧味与时令菜；具体菜单和价格以当天为准。",
    itinerary: ["只在同行人数增加或临时想吃完整粤菜时选择。", "先问等位、茶位、服务费与菜量。", "吃完直接打车回住宿区或返程。"],
    tips: ["两个人不宜照多人榜单点菜。", "公开评价样本较少且分散，现场菜单比旧攻略可靠。", "不列入主线，避免为用餐跨城折返。"],
    source: "https://cn.tripadvisor.com/Restaurant_Review-g494927-d4565234-Reviews-ShunFeng_ShanZhuang-Foshan_Guangdong.html",
    researchSources: [["佛山本地报道中的顺峰山庄", "https://www.foshannews.net/"], ["游客餐厅评价参考", "https://cn.tripadvisor.com/Restaurant_Review-g494927-d4565234-Reviews-ShunFeng_ShanZhuang-Foshan_Guangdong.html"]]
  },
  {
    id: "sd-baolin", city: "顺德", area: "大良", category: "人文",
    name: "宝林寺（顺峰山加长支线）", lat: 22.8153133, lng: 113.2719101,
    duration: "1–2 小时", best: "体力充足且愿意爬台阶", transit: "位于顺峰山片区；与公园主入口并非一步之遥",
    summary: "只在愿意爬坡、减少后续项目时加入；不属于省力主线。",
    description: "宝林寺可作为顺峰山的加长版本，但会增加台阶、交通与停留时间。两天行程已较满，默认不去比强塞进去更舒服。",
    features: "寺院建筑与山地视角，体验和湖边公园不同。",
    playability: "适合对寺院建筑有明确兴趣的人；普通散步需求留在公园主入口即可。",
    itinerary: ["先完成顺峰山核心段。", "确认体力和开放情况后再决定。", "若加入，取消或缩短博物馆。"],
    tips: ["着装得体并遵守场所规则。", "台阶与坡度会增加体力消耗。", "开放与入场要求以当天现场为准。"],
    source: "https://www.openstreetmap.org/"
  },
  {
    id: "sd-rongbian", city: "顺德", area: "容桂·容边", category: "美食", rongguiFood: true,
    name: "容边排骨饭（容边天河路店）", pinName: "容桂｜容边排骨饭", lat: 22.74643, lng: 113.30601,
    duration: "45–75 分钟", best: "D2-B 早午餐；尽量 10:30 前", transit: "容边天河路 7 号一带；从国泰南路住宿区网约车约 20–30 分钟",
    summary: "容桂线的主餐落点：干蒸排骨配米饭，适合早去；它与几个近似店名不是同一家，导航务必核对完整店名和门牌。",
    description: "把这顿放在早午餐，是因为公开平台常见营业时段偏早且可能售罄。两个人先点一份排骨饭，再按胃口加青菜或汤，不为探店一次点满。",
    features: "街坊式排骨饭，重点是排骨肉汁落入米饭的干蒸做法；环境与出餐更接近日常早餐、午饭档。",
    playability: "观察当天排队与售罄情况；超过可接受等位就转红星光发，不在相似店名之间盲猜。",
    food: "主吃干蒸排骨饭。容边排骨饭、容边御品排骨饭、容边聚源及达汉珍等名称相近，本地图不把它们视为同店。",
    itinerary: ["约 09:30 到店，先核对“容边天河路店”和门牌。", "两个人先合点一份主食，再决定是否加菜。", "饭后按体力去柴油机1959；不想看旧厂可直接休息，傍晚再到渔人码头。"],
    tips: ["公开平台常见营业到午后早段，但国庆营业、售罄和排队必须出发前复核。", "相似店名很多，导航不要只搜“排骨饭”。", "早餐或小吃等位超过 15–20 分钟即可启用替换店。"],
    source: "https://tw.trip.com/restaurant/china/foshan/detail/rongbian-pork-chop-rice-42415426/",
    researchSources: [["Trip：门店页与菜式参考", "https://tw.trip.com/restaurant/china/foshan/detail/rongbian-pork-chop-rice-42415426/"], ["大众点评：容边排骨饭门店页", "https://m.dianping.com/shop/94281484?msource=applemaps"], ["探店视频：排骨饭出品参考", "https://www.youtube.com/watch?v=Eohxm1ev5lE"]]
  },
  {
    id: "sd-diesel1959", city: "顺德", area: "容桂·旧工业区", category: "人文",
    name: "柴油机1959文创园", lat: 22.77775, lng: 113.26635,
    duration: "60–90 分钟", best: "D2-B 午后可选", transit: "工业路 23 号；从容边网约车约 15–25 分钟",
    summary: "旧厂房改造的容桂工业记忆点；作为午后可选项，不为凑打卡牺牲休息，也不假设所有店铺都营业。",
    description: "园区保留旧工业建筑尺度，适合在正餐与傍晚江边之间短逛。文创店、咖啡与展陈会随运营变化，出发前看最新营业信息。",
    features: "顺德制造业旧址、厂房空间与当代商业更新叠在一起，比纯商业街更有容桂本地工业背景。",
    playability: "看建筑、拍旧厂细节、找一处坐下休息；60–90 分钟足够，不必逐店完成。",
    itinerary: ["排骨饭后先看天气与体力。", "想看旧厂就来短逛；疲惫则取消。", "下午留足休息，约 16:00 步行去渔人码头。"],
    tips: ["园内租户与开放状态会变，以当天现场为准。", "正午炎热时减少室外停留。", "地图按工业路 23 号标注，入口以导航为准。"],
    source: "https://www.google.com/maps/search/?api=1&query=%E6%9F%B4%E6%B2%B9%E6%9C%BA1959%E6%96%87%E5%88%9B%E5%9B%AD%20%E4%BD%9B%E5%B1%B1%E9%A1%BA%E5%BE%B7",
    researchSources: [["地址与园区地图入口", "https://www.google.com/maps/search/?api=1&query=%E6%9F%B4%E6%B2%B9%E6%9C%BA1959%E6%96%87%E5%88%9B%E5%9B%AD%20%E4%BD%9B%E5%B1%B1%E9%A1%BA%E5%BE%B7"]]
  },
  {
    id: "sd-ronggui-wharf", city: "顺德", area: "容桂·东堤", category: "城市",
    name: "容桂渔人码头", lat: 22.78075, lng: 113.27104,
    duration: "60–90 分钟", best: "D2-B 16:00 后看江景", transit: "东堤路 16 号一带；从柴油机1959步行约 5–10 分钟",
    summary: "由旧码头与工业遗存更新的滨水街区，适合傍晚散步、看江面和旧厂建筑；它是轻量收尾，不是全天景区。",
    description: "渔人码头与柴油机1959距离近，适合连走。把核心放在傍晚江边与旧建筑，不需要为了餐饮店或拍照点反复绕行。",
    features: "德胜河滨水空间、旧食品厂与码头记忆、更新后的街区商业混合在一起。",
    playability: "沿江慢走、坐下看天色，再按真实饥饿程度决定是否去灵记；不饿就直接返程。",
    itinerary: ["约 16:00 从柴油机1959一带步行过来。", "沿江走 60–90 分钟，优先看日落前后光线。", "17:30 后真饿再去附近灵记，不把烧烤当必吃任务。"],
    tips: ["天气、江风和节假日人流会明显影响体验。", "部分区域为开放街区，不要按封闭景区方式赶点。", "返程时间按实际车票与交通倒推。"],
    source: "https://www.shunde.gov.cn/fssdrg/gkmlpt/content/6/6035/post_6035900.html#3831",
    researchSources: [["容桂街道官方：渔人码头更新背景", "https://www.shunde.gov.cn/fssdrg/gkmlpt/content/6/6035/post_6035900.html#3831"]]
  },
  {
    id: "sd-lingji-ronggui", city: "顺德", area: "容桂·渔人码头", category: "美食", rongguiFood: true,
    name: "建港灵记美食·烧烤（渔人码头店）", pinName: "容桂｜灵记烧烤", lat: 22.78100, lng: 113.27030,
    duration: "60–90 分钟", best: "D2-B 傍晚；真饿再吃", transit: "滨河路 8 号地块 L10；从渔人码头核心区步行约 5–10 分钟",
    summary: "容桂线的江边晚餐备选；公开资料对稳定招牌菜证据不够集中，因此以当天菜单、排队和真实饥饿程度决定。",
    description: "排骨饭已经是当天主餐，灵记只在傍晚真饿时加入。先看现场菜单、最小份量与等位，不因为“到过渔人码头”就强行完成第二顿大餐。",
    features: "烧烤与晚间聚餐氛围更匹配渔人码头时段，但菜单、营业与客流可能随节假日变化。",
    playability: "把它当一顿可取消的夜食：短等位、少量点、吃完直接返程。",
    food: "优先根据当天菜单点两人可分的小份；它排名靠后，不把热度当成口味保证。",
    itinerary: ["先完成江边散步，再判断是否真的饿。", "到店先问等位、份量与当日供应。", "不饿或排队过长就取消，直接按返程导航离开容桂。"],
    tips: ["出发前用完整店名与“滨河路 8 号地块 L10”复核分店。", "不与其他同名或近似烧烤店混为一家。", "节假日营业和排队以门店当天信息为准。"],
    source: "https://map.baidu.com/?newmap=1&s=inf%26uid%3D589c1202c7089ffa373a71ea%26wd%3D%E5%BB%BA%E6%B8%AF%E7%81%B5%E8%AE%B0%E7%BE%8E%E9%A3%9F%28%E6%B8%94%E4%BA%BA%E7%A0%81%E5%A4%B4%E5%BA%97%29%26all%3D1%26c%3D138&from=alamap&tpl=map_singlepoint",
    researchSources: [["百度地图：门店与地址复核", "https://map.baidu.com/?newmap=1&s=inf%26uid%3D589c1202c7089ffa373a71ea%26wd%3D%E5%BB%BA%E6%B8%AF%E7%81%B5%E8%AE%B0%E7%BE%8E%E9%A3%9F%28%E6%B8%94%E4%BA%BA%E7%A0%81%E5%A4%B4%E5%BA%97%29%26all%3D1%26c%3D138&from=alamap&tpl=map_singlepoint"]]
  },
  {
    id: "sd-hongxing-guangfa", city: "顺德", area: "容桂·文海", category: "美食", rongguiFood: true,
    name: "红星光发煲仔饭（文海店）", pinName: "容桂｜红星光发", lat: 22.75041, lng: 113.27732,
    duration: "45–75 分钟", best: "容边排骨饭售罄或不想早起时", transit: "文海西路 7 号丽枫酒店底铺；建议网约车",
    summary: "容桂替换餐：想吃煲仔饭、没赶上排骨饭早档，或容边等位过长时再选；不与排骨饭连吃。",
    description: "这家承担的是替换功能，不是新增一餐。公开营业时段与口感评价可能变化，出发前复核；到店先问现做等待时间和小份选择。",
    features: "煲仔饭适合作为较规律的午晚餐，但现煲等待、锅巴程度与节假日客流会影响体验。",
    playability: "把它设为容边排骨饭的 Plan B；一旦选择，就直接重排后续时间，不再回头补吃排骨饭。",
    food: "按两人份量选一锅或小份主食，先问制作等待和当日售罄菜式。",
    itinerary: ["容边售罄、等位超过 15–20 分钟或不想早起时启用。", "吃完再决定去柴油机1959或直接休息。", "不要与排骨饭、灵记连续堆成三顿。"],
    tips: ["导航核对文海西路 7 号文海店。", "公开平台常见午、晚分段营业，但国庆时段请当天复核。", "口感评价主观，以现场出品为准。"],
    source: "https://www.google.com/maps/search/?api=1&query=%E7%BA%A2%E6%98%9F%E5%85%89%E5%8F%91%E7%85%B2%E4%BB%94%E9%A5%AD%20%E6%96%87%E6%B5%B7%E8%A5%BF%E8%B7%AF7%E5%8F%B7",
    researchSources: [["地址地图入口", "https://www.google.com/maps/search/?api=1&query=%E7%BA%A2%E6%98%9F%E5%85%89%E5%8F%91%E7%85%B2%E4%BB%94%E9%A5%AD%20%E6%96%87%E6%B5%B7%E8%A5%BF%E8%B7%AF7%E5%8F%B7"]]
  },
  {
    id: "sd-desheng-river", city: "顺德", area: "大良新城", category: "公园",
    name: "德胜河滨公园（安静替代）", lat: 22.7813816, lng: 113.2967380,
    duration: "1–1.5 小时", best: "傍晚", transit: "从国泰南路住宿区短途网约车",
    summary: "不想逛主题街区时，用河边散步替换欢乐海岸，不与主线叠加。",
    description: "它是第二天傍晚的安静替代项：如果已经疲惫、不想排队或不玩付费项目，就到河边短走，之后直接返程。",
    features: "城市河岸、开阔视野和轻量散步，商业密度低于欢乐海岸。",
    playability: "坐一会、吹风、看傍晚光线；不追求走完整段。",
    itinerary: ["午休后按天气与体力二选一。", "选择这里就不再去欢乐海岸。", "按返程票倒推离开时间。"],
    tips: ["作为替代项而不是新增打卡点。", "雨天或大风时改为室内。", "夜间照明与出口以现场为准。"],
    source: "https://www.openstreetmap.org/"
  },
  {
    id: "sd-weikedao", city: "顺德", area: "大良·新桂中路一带", category: "美食", pendingLocation: true,
    name: "味可道（大良店，分店待复核）", pinName: "TOP5｜味可道", lat: 22.85047, lng: 113.25838,
    duration: "60–90 分钟", best: "早茶时段；出发前核对分店", transit: "地图针为新桂中路片区参考，请用完整店名确认仍营业的分店",
    summary: "两篇早茶横评中，烧卖、肠粉和粥的反馈较具体；虾饺评价有分歧，适合作为一顿早茶替换项。",
    description: "研究样本里对味可道的有效信息来自逐道比较，而不是只报店名。因为公开资料中的分店信息会变化，本图先保留片区参考点，不把旧地址当作精确门口。",
    features: "传统早茶品类较完整，适合两个人选三四样分食。",
    playability: "只替换一顿早餐或午前正餐，不与大围公、乐园酒家连续吃。",
    food: "优先看烧卖、肠粉和粥的当天出品；虾饺先点一笼，不按网红清单一次点满。",
    itinerary: ["出发前在地图核对仍营业的具体分店。", "到店先问茶位、等位和点心供应。", "两人少量分点，吃完再走附近老城。"],
    tips: ["当前坐标是片区参考，不是精确店门。", "分店、营业时段和菜单以当天门店为准。", "一旦选择本店，就删掉同日其他早茶。"],
    source: "https://www.google.com/maps/search/?api=1&query=%E5%91%B3%E5%8F%AF%E9%81%93%20%E9%A1%BA%E5%BE%B7%E5%A4%A7%E8%89%AF"
  },
  {
    id: "sd-aduo", city: "顺德", area: "大良南部", category: "美食", pendingLocation: true,
    name: "阿多私房菜（大良店，地址待复核）", pinName: "TOP6｜阿多私房菜", lat: 22.8212, lng: 113.2528,
    duration: "1.5–2 小时", best: "替换一顿正餐；先订位", transit: "地图针为大良南部片区参考，出发前按完整店名核对最新地址",
    summary: "桑拿鸡横评中，鸡肉和汤获具体好评，但客单和份量更适合把它当完整正餐。",
    description: "阿多在样本里不是单靠高频入选，而是有对鸡肉、汤底和价格的具体描述。两个人去要先问最小份量，避免为了比较桑拿鸡再叠加百益。",
    features: "私房菜与桑拿鸡体验，适合坐下来完成一顿饭。",
    playability: "与百益二选一；愿意为环境与完整正餐多留时间时再去。",
    food: "优先问桑拿鸡最小份、配菜和汤底；价格偏高是研究中反复出现的取舍。",
    itinerary: ["先核对分店、地址和订位。", "问清两人份量再下单。", "吃完直接接下一景点，不再补吃另一家桑拿鸡。"],
    tips: ["当前坐标为片区参考。", "价格、包间与最低消费以当天为准。", "与百益功能重叠，二选一。"],
    source: "https://www.google.com/maps/search/?api=1&query=%E9%98%BF%E5%A4%9A%E7%A7%81%E6%88%BF%E8%8F%9C%20%E9%A1%BA%E5%BE%B7%E5%A4%A7%E8%89%AF"
  },
  {
    id: "sd-tidi", city: "顺德", area: "大良·金榜", category: "美食", pendingLocation: true,
    name: "梯底牛乳铺", pinName: "TOP8｜梯底牛乳铺", lat: 22.84045, lng: 113.2428,
    duration: "15–30 分钟", best: "走金榜上街时顺路", transit: "金榜上街片区；地图针为街区参考，按当天导航找店",
    summary: "甜品横评里反复出现，但口感评价两极：有人喜欢淡而稠，也有人觉得腻，适合两人合点一份。",
    description: "梯底牛乳铺的价值在于和金榜老街同线，不值得为了一个甜品远距离折返。把它当现场比较项，排队长或已经吃过奶制品就跳过。",
    features: "顺德水牛奶甜品小店，和金榜街区的老街体验绑定。",
    playability: "短停、分食、现场决定，不做必吃任务。",
    food: "先选一种奶制品共享；同一天不再连续测试多家双皮奶。",
    itinerary: ["先逛金榜上街再看排队。", "两人合点一份。", "口味不合就停止，不继续追榜。"],
    tips: ["坐标为金榜片区参考。", "甜度与稠度非常主观。", "和民信、其他金榜奶店只选一到两家。"],
    source: "https://www.google.com/maps/search/?api=1&query=%E6%A2%AF%E5%BA%95%E7%89%9B%E4%B9%B3%E9%93%BA%20%E9%A1%BA%E5%BE%B7"
  },
  {
    id: "sd-shaoezai", city: "顺德", area: "大良", category: "美食", pendingLocation: true,
    name: "烧鹅再（大良店，地址待复核）", pinName: "TOP9｜烧鹅再", lat: 22.8348, lng: 113.2525,
    duration: "45–75 分钟", best: "午市较早到店", transit: "地图针为大良老城片区参考，出发前核对分店与门牌",
    summary: "四家烧鹅横评中的候选；适合小份共享，肥瘦、出炉批次、排队和售罄都会改变体验。",
    description: "烧鹅提及很多但门店分散，本版只保留与大良行程相容的候选，不为了凑榜跨区。具体分店仍需出发前确认。",
    features: "烧鹅适合做老城小份加餐或替换一顿简餐。",
    playability: "看到合适斩料和短队再吃；售罄就放弃，不跨区追烧鹅。",
    food: "两人先问能否点小份，并说明想要的肥瘦；不与大正餐叠加。",
    itinerary: ["当天地图核对门店。", "午市较早到，先问出炉与售罄。", "小份共享后继续老城步行。"],
    tips: ["当前坐标不是精确店门。", "分店评价不能混用。", "售罄或排队长就跳过。"],
    source: "https://www.google.com/maps/search/?api=1&query=%E7%83%A7%E9%B9%85%E5%86%8D%20%E5%A4%A7%E8%89%AF%E5%BA%97"
  },
  {
    id: "sd-weiji-niuza", city: "顺德", area: "大良老城", category: "美食", pendingLocation: true,
    name: "韦记牛杂（清晖园店）", pinName: "TOP10｜韦记牛杂", lat: 22.8379, lng: 113.2490,
    duration: "15–30 分钟", best: "华盖路顺路加餐", transit: "清晖园、华盖路片区；地图针为街区参考",
    summary: "老城路线里最容易顺带的一口牛杂；入选靠动线和评论中的具体点单，不建议为它长排队。",
    description: "韦记适合作为清晖园与华盖路之间的小吃，而不是独立目的地。两个人共享一小份即可，把胃口留给真正的主餐。",
    features: "老城街头小吃，停留短、替换成本低。",
    playability: "队短就吃，队长就继续走；附近同类很多。",
    food: "点一小份牛杂共享，先问辣度和当日部位。",
    itinerary: ["清晖园或华盖路途中看排队。", "小份共享。", "不影响琼花戏楼预约时间。"],
    tips: ["坐标为清晖园商圈参考。", "不要为小吃耽误预约正餐。", "当天售完或队长可直接替换。"],
    source: "https://www.google.com/maps/search/?api=1&query=%E9%9F%A6%E8%AE%B0%E7%89%9B%E6%9D%82%20%E6%B8%85%E6%99%96%E5%9B%AD%E5%BA%97"
  },
  {
    id: "sd-mandengdeng", city: "顺德", area: "容桂·江南大道", category: "美食", rongguiFood: true, pendingLocation: true,
    name: "满登登·顺德特色菜", pinName: "容桂TOP11｜满登登", lat: 22.7658, lng: 113.2715,
    duration: "1–1.5 小时", best: "午餐或晚餐替换项", transit: "江南大道 23 号容莲宾馆 2 楼；地图针为地址片区参考",
    summary: "容桂本地名单中辨识度较高，黄鳝煲仔饭可作为主餐；选它就不要再把排骨饭和煲仔饭全塞进一天。",
    description: "满登登补足了容桂不只有排骨饭和烧烤。它更适合替换容桂线的一顿主餐，而不是在排骨饭之后继续加餐。",
    features: "顺德家常菜与黄鳝煲仔饭，适合两人完整吃一顿。",
    playability: "想吃桌菜或不想赶排骨饭早档时选它。",
    food: "黄鳝煲仔饭是辨识度较高的选择；再加一份青菜即可。",
    itinerary: ["出发前核对容莲宾馆内入口与营业。", "两人按一顿主餐点单。", "饭后选旧厂或码头，不再补排骨饭。"],
    tips: ["地图针为地址片区参考。", "与红星光发、容边排骨饭三选一主食。", "问清煲仔饭等待时间。"],
    source: "https://www.google.com/maps/search/?api=1&query=%E6%BB%A1%E7%99%BB%E7%99%BB%20%E9%A1%BA%E5%BE%B7%E7%89%B9%E8%89%B2%E8%8F%9C%20%E6%B1%9F%E5%8D%97%E5%A4%A7%E9%81%9323%E5%8F%B7"
  },
  {
    id: "sd-leyuan", city: "顺德", area: "容桂·桂洲", category: "美食", rongguiFood: true, pendingLocation: true,
    name: "乐园酒家", pinName: "容桂TOP12｜乐园酒家", lat: 22.7628, lng: 113.2570,
    duration: "1–1.5 小时", best: "早茶或多人粤菜", transit: "桂洲居委会路心西街 46 号；地图针为街区参考",
    summary: "容桂老字号早茶和传统粤菜候选；品类多，更适合早餐或人数增加时分食。",
    description: "乐园酒家提供了容桂传统酒楼路线。两个人也能去，但要用早茶思路少量分点；若已经安排味可道或大围公，就不要再加。",
    features: "老式酒楼环境、早茶点心和粤菜。",
    playability: "想看容桂日常早茶氛围时，比追单一网红小吃更完整。",
    food: "按当天点心车或菜单选三四样，不照多人推荐单全点。",
    itinerary: ["早上核对营业和排队。", "问茶位、服务费与点心供应。", "吃完再开始容桂片区游玩。"],
    tips: ["地图针为路心西街片区参考。", "更适合早茶或多人。", "与其他早茶店二选一。"],
    source: "https://www.google.com/maps/search/?api=1&query=%E4%B9%90%E5%9B%AD%E9%85%92%E5%AE%B6%20%E5%AE%B9%E6%A1%82%20%E8%B7%AF%E5%BF%83%E8%A5%BF%E8%A1%9746%E5%8F%B7"
  },
  {
    id: "sd-zhenzhibao", city: "顺德", area: "容桂·渔人码头", category: "美食", rongguiFood: true, pendingLocation: true,
    name: "珍之宝御品·寻味顺德（渔人码头店）", pinName: "容桂TOP13｜珍之宝", lat: 22.7814, lng: 113.2697,
    duration: "1–1.5 小时", best: "码头段的早茶或正餐", transit: "滨河路君润商业大厦君领广场 401 / 501；地图针为楼宇片区参考",
    summary: "胜在和渔人码头同区；不想吃烧烤或需要室内坐下时，可替换灵记。",
    description: "珍之宝的排名更多来自位置便利和早茶样本，不代表口味证据强过前列门店。它在容桂线承担的是天气、体力和同行需求变化时的室内替换。",
    features: "早茶与顺德菜，靠近渔人码头，适合多人或想坐下休息。",
    playability: "和灵记二选一；先逛码头再看是否需要完整正餐。",
    food: "按人数选点心或一顿正餐，先问茶位、服务费和等位。",
    itinerary: ["码头散步前后判断是否需要正餐。", "到楼内按当天导视找店。", "选了本店就取消烧烤。"],
    tips: ["地图针为商业楼宇参考。", "位置优势大于口味证据。", "与灵记二选一。"],
    source: "https://www.google.com/maps/search/?api=1&query=%E7%8F%8D%E4%B9%8B%E5%AE%9D%E5%BE%A1%E5%93%81%20%E5%AE%B9%E6%A1%82%E6%B8%94%E4%BA%BA%E7%A0%81%E5%A4%B4"
  },
  {
    id: "sd-hem", city: "顺德", area: "北滘", category: "人文",
    name: "和美术馆", lat: 22.9356181, lng: 113.2146984,
    duration: "2–3 小时", best: "按预约时段", transit: "北滘新城片区；建议与岭南和园组成半日线",
    summary: "建筑与当代艺术是核心；北滘离两日主线较远，应替换半天而不是临时加塞。",
    description: "和美术馆适合对建筑和当代艺术有明确兴趣的人。开放、展览、票务与预约会变化，出发前以官网为准。",
    features: "清水混凝土建筑、旋转楼梯和当代艺术展览。",
    playability: "看一场展和建筑空间即可，不必与大良、容桂同日来回。",
    itinerary: ["官网查开放、展览与购票。", "预留两到三小时。", "步行或短途车接岭南和园。"],
    tips: ["周一等闭馆规则以官网为准。", "展览内容会更换。", "北滘单独成线。"],
    source: "https://www.hem.org/"
  },
  {
    id: "sd-lingnan-heyuan", city: "顺德", area: "北滘", category: "人文",
    name: "岭南和园", lat: 22.9381359, lng: 113.2067516,
    duration: "1.5–2 小时", best: "上午或傍晚前", transit: "北滘片区；与和美术馆短途转场",
    summary: "岭南园林和非遗展示集中，适合与和美术馆组合成北滘半日。",
    description: "岭南和园比大良主线更偏园林与非遗专题。已经看过清晖园仍可去，但两者最好分在不同半天。",
    features: "岭南园林、新建园景与非遗展示。",
    playability: "慢走核心园区，按当天活动决定是否多留。",
    itinerary: ["先核对开放与购票。", "走核心园景。", "与和美术馆二点组合。"],
    tips: ["不要和清晖园同日赶场。", "活动以当天公告为准。", "北滘单独成线。"],
    source: "https://www.openstreetmap.org/?mlat=22.9381359&mlon=113.2067516#map=17/22.9381359/113.2067516"
  },
  {
    id: "sd-bijiang-jinlou", city: "顺德", area: "北滘·碧江", category: "人文",
    name: "碧江金楼", lat: 22.9453161, lng: 113.2571943,
    duration: "1.5–2 小时", best: "白天开放时段", transit: "碧江片区；建议网约车并预留返程",
    summary: "金漆木雕、古宅和村落肌理是亮点；适合历史建筑爱好者，位置不顺大良主线。",
    description: "碧江金楼是顺德古建候选里辨识度较高的一处。距离大良与容桂主线都有转场成本，只在愿意为古建单独留半天时加入。",
    features: "古宅、金漆木雕与岭南村落空间。",
    playability: "细看木雕和院落，周边只做轻量村落步行。",
    itinerary: ["核对开放和票务。", "主看金楼古建。", "按返程时间离开碧江。"],
    tips: ["开放与维护以当天公告为准。", "村内步行注意居民生活。", "不要塞进大良老城同日。"],
    source: "https://www.openstreetmap.org/?mlat=22.9453161&mlon=113.2571943#map=17/22.9453161/113.2571943"
  },
  {
    id: "sd-lunjiao-678", city: "顺德", area: "伦教", category: "人文",
    name: "伦教678文化街", lat: 22.8806253, lng: 113.2637245,
    duration: "1–2 小时", best: "午后到傍晚", transit: "伦教老街片区；建议网约车",
    summary: "旧街活化、社区尺度和香云纱文化可串联；适合慢逛，不是大型封闭景区。",
    description: "678文化街是一段片区体验，店铺开闭会变化。把它和香云纱专题安排在同一半天，比从大良单点往返更合理。",
    features: "旧街更新、社区空间与小型文创店。",
    playability: "慢走一到两小时，遇到有兴趣的店再停。",
    itinerary: ["从老街入口开始。", "沿支巷慢走。", "按开放情况接香云纱点位。"],
    tips: ["部分店铺可能晚开或休息。", "尊重居民生活。", "与香云纱片区组合。"],
    source: "https://www.openstreetmap.org/?mlat=22.8806253&mlon=113.2637245#map=17/22.8806253/113.2637245"
  },
  {
    id: "sd-fengling", city: "顺德", area: "大良老城", category: "公园",
    name: "凤岭公园", lat: 22.8446806, lng: 113.2433117,
    duration: "30–60 分钟", best: "清晨或傍晚", transit: "金榜与钟楼站附近，适合作为顺路休息段",
    summary: "大良老城里的绿地和短上坡；只做顺路休息，不值得为它改主线。",
    description: "凤岭公园最大的价值是位置：走累时可把它作为老城边缘的绿地休息段。",
    features: "城市公园、树荫与短距离步行。",
    playability: "停半小时、散步或坐一会即可。",
    itinerary: ["金榜附近看体力决定。", "只走短段。", "从最近出口继续老城线。"],
    tips: ["不作为必到点。", "雨天跳过。", "夜间按现场照明选择路线。"],
    source: "https://www.openstreetmap.org/?mlat=22.8446806&mlon=113.2433117#map=17/22.8446806/113.2433117"
  },
  {
    id: "sd-xishan-temple", city: "顺德", area: "大良老城", category: "人文",
    name: "西山庙", lat: 22.8427876, lng: 113.2475693,
    duration: "30–60 分钟", best: "白天顺路", transit: "靠近大良钟楼站，可作 D1 起点旁小支线",
    summary: "钟楼站附近的古建小支线；对庙宇建筑有兴趣再进，不影响金榜—清晖园主线。",
    description: "西山庙的优势是紧邻起点。到站早、体力好可短看；若时间紧，直接去金榜上街。",
    features: "老城庙宇建筑与地方历史。",
    playability: "短看建筑细节，不需要单独留半天。",
    itinerary: ["到钟楼站后看时间。", "开放则短逛。", "原路接金榜上街。"],
    tips: ["开放以现场为准。", "着装得体。", "不压缩清晖园预约时间。"],
    source: "https://www.openstreetmap.org/?mlat=22.8427876&mlon=113.2475693#map=18/22.8427876/113.2475693"
  },
  {
    id: "sd-xiangyunsha", city: "顺德", area: "伦教", category: "人文",
    name: "香云纱博物馆 / 文化体验点", lat: 22.8619590, lng: 113.2148943,
    duration: "1–2 小时", best: "确认开放或预约后", transit: "伦教片区；建议和678文化街组合",
    summary: "了解香云纱染整工艺的专题点；开放和预约比一般景点更需要提前确认。",
    description: "香云纱是顺德很有地方性的工艺，但相关展示点、活动和参观规则可能变化。本图标注文化片区参考点，出发前必须核对可进入的具体场馆。",
    features: "香云纱面料、染整流程与非遗背景。",
    playability: "有讲解或工艺展示时价值更高；仅看静态陈列则控制停留。",
    itinerary: ["提前确认场馆名称和预约。", "按讲解时段到达。", "与伦教老街组合。"],
    tips: ["先确认是否对散客开放。", "活动日期可能不固定。", "地图点为文化片区参考。"],
    source: "https://www.openstreetmap.org/?mlat=22.8619590&mlon=113.2148943#map=16/22.8619590/113.2148943"
  },
  {
    id: "sd-brucelee", city: "顺德", area: "均安", category: "人文",
    name: "李小龙乐园", lat: 22.7199825, lng: 113.1187661,
    duration: "2–3 小时", best: "白天", transit: "均安片区，离大良和容桂主线较远，建议单独成线",
    summary: "功夫文化主题与生态园结合；距离远，只推荐给对李小龙主题有明确兴趣的人。",
    description: "李小龙乐园在顺德西南侧，交通成本明显高于榜单前列地点。它入前20是因为主题独特，不代表两日主线必须去。",
    features: "李小龙主题展示、雕塑与园区空间。",
    playability: "主题粉丝可留半天；普通游客优先大良、北滘或容桂。",
    itinerary: ["核对开放和票务。", "预留往返交通。", "游览后不要再跨区赶大良景点。"],
    tips: ["位置偏远。", "开放项目以当天为准。", "两日主线默认不放入。"],
    source: "https://www.openstreetmap.org/?mlat=22.7199825&mlon=113.1187661#map=16/22.7199825/113.1187661"
  },
  {
    id: "sd-snoopy", city: "顺德", area: "大良新城", category: "乐园",
    name: "史努比缤纷世界", lat: 22.7975912, lng: 113.3049941,
    duration: "3–5 小时", best: "亲子家庭白天", transit: "大良新城片区；从国泰南路住宿区短途网约车",
    summary: "小体量亲子主题乐园；有儿童同行时价值更高，无儿童则排在榜单末位。",
    description: "史努比缤纷世界靠近住宿锚点，但客群很明确。带低龄儿童可替换博物馆或欢乐海岸；成人两人行不建议只因榜单前往。",
    features: "史努比主题布景、亲子游乐与演出。",
    playability: "适合低龄亲子半日，成人拍照需求可短停。",
    itinerary: ["先看当天票务和演出。", "挑适龄项目。", "按午休和返程时间离园。"],
    tips: ["儿童项目年龄身高限制以现场为准。", "室外项目受天气影响。", "无儿童同行优先级较低。"],
    source: "https://www.openstreetmap.org/?mlat=22.7975912&mlon=113.3049941#map=17/22.7975912/113.3049941"
  }
]);

const fengjian = extraPlaces.find(place => place.id === "sd-fengjian");
if (fengjian) Object.assign(fengjian, { lat: 22.8156353, lng: 113.1491122 });

shundeFoodResearch.ranking.forEach(item => {
  const place = extraPlaces.find(candidate => candidate.id === item.placeId);
  if (place) Object.assign(place, { foodTopRank: item.rank, foodSignal: item.signal });
});
shundeFoodResearch.playRanking.forEach(item => {
  const place = extraPlaces.find(candidate => candidate.id === item.placeId);
  if (place) place.playTopRank = item.rank;
});

destinationGuides["顺德"] = {
  intro: "本版去重阅读 57 篇游记、探店正文及可见评论，再用 10 个官网、地图与评价页复核，共 67 条资料；已把前 20 个美食落点和前 20 个值得玩地点标进地图。D1 走大良老城，D2-A 大良新城与 D2-B 容桂二选一；北滘、伦教、均安远点只作换线备选。",
  foods: [
    ["前 20 美食已全部落图", "榜单综合提及、具体好评、负评可信度、两人可操作性与动线，不等同于平台星级；用“美食TOP20”可单独筛选。"],
    ["容桂不止三家", "榜单内已有容边排骨饭、满登登、乐园酒家、珍之宝、红星光发和灵记；选主餐时互相替换，不建议一天全部连吃。"],
    ["甜品与粥底火锅", "民信、梯底和金榜奶制品只选一两样分食；太艮堡与赋狮楼只选一家。"],
    ["桑拿鸡与烧鹅", "百益、阿多二选一；烧鹅再仅作为大良顺路候选，分店、出炉和售罄须当天复核。"],
    ["鱼类风险", "淡水鱼生不进主路线；如去新顺发，只建议选择彻底熟制的一鱼多吃菜式。孕妇、儿童、老年人及免疫力较弱者不建议生食。"],
    ["D1 主餐：琼花戏楼", "华盖里四巷 14 号；优先按演出时段预约。它与赋狮楼二选一顿大餐，不连吃。"],
    ["D1 早餐：金榜上街少量探索", "双皮奶、姜撞奶、水牛奶或炸牛奶只选一两样分食；甜度和口味评价分歧大，以现场为准。"],
    ["晚餐备选：赋狮楼粥底火锅", "碧鉴路 56 号；午餐后真饿再去。鱼片或鸡肉少量分批涮，最后尝粥底。"],
    ["D2-B 主餐：容边排骨饭", "尽量早到容边天河路店；核对完整店名与门牌。售罄或等位超过 15–20 分钟时，改红星光发，不把近似店名混为一家。"],
    ["D2-B 夜食：灵记烧烤", "渔人码头散步后真饿再吃；按当天菜单少量点，不饿或排队过长就取消。"],
    ["容桂替换餐：红星光发煲仔饭", "文海店只作为容边排骨饭的 Plan B，不与排骨饭连续吃。公开营业时段在国庆前需再次确认。"],
    ["早餐支线：大围公", "大围六街三巷 10 号之一；粥、肉碎肠粉、油条、豆浆。只在 D2-A 愿意早起时加入。"],
    ["多人备选：顺峰山庄", "更适合多人分菜；两个人先问茶位、服务费和小份菜，不列入省力主线。"],
    ["关于预制菜", "龙的酒楼不纳入路线。其他门店也不做“完全无预制”保证；介意时现场逐道询问制作与备料方式。"]
  ]
};
